### ISSUE TITLE
Specifically crafted message causes NPE

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/rlo_06#6]
```sh
tcpflood -t 127.0.0.1 -T relp-plain -p 1601 -M "<999>1    - - -"
```

causes

```sh
java.lang.NullPointerException: null
        at com.teragrep.rlo_06.RFC5424Parser.parseMSG(RFC5424Parser.java:334)
        at com.teragrep.rlo_06.RFC5424Parser.next(RFC5424Parser.java:585)
<snip>
```

**Comment by kortemik** [comment]
please re-test
