### ISSUE TITLE
ArrayIndexOutOfBoundsException on specifically crafted invalid message

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/rlo_06#7]
```sh
tcpflood -t 127.0.0.1 -T relp-plain -p 1601 -M "<134>1 2018-01-01T10:12:00+01:00 logsrc-tcpflood tcpflood - - [ - - "
```

causes

```sh
        at com.teragrep.rlo_06.RFC5424Parser.readBuffer(RFC5424Parser.java:89)
        at com.teragrep.rlo_06.RFC5424Parser.parseSD(RFC5424Parser.java:295)
        at com.teragrep.rlo_06.RFC5424Parser.next(RFC5424Parser.java:578)
```

**Comment by kortemik** [comment]
please re-test
